### ISSUE TITLE
Swoft Support.

### ISSUE THREAD

**Issue by huangzhhui** [medz/cors#6]
Great middleware, Is it possible to support [Swoft](https://github.com/swoft-cloud/swoft) framework ?

**Comment by medz** [comment]
Yep, thank you for your suggestion. I have observed swoft after receiving the notification from Issue. swoft is using PSR-7, so this middleware is supported, but you need to inject yourself, and swoft's middleware specification uses PSR-15 is also my next step. You can refer to the [Using PSR-7](https://github.com/medz/cors#psr-7) document first. After supporting PSR-15, I will reply this Issue. Thank you again for your suggestion.

**Comment by medz** [comment]
https://github.com/medz/cors#psr-7

**Comment by medz** [comment]
@huangzhhui 你好，我已经上传了 PSR-15 的支持代码。你是否有兴趣添加 SWOFT 的支持代码呢？

**Comment by medz** [comment]
See https://github.com/medz/cors/commit/13c136738a70f1f164217aa150473650416b6479
