### ISSUE TITLE
Access-Control-Max-Age 没设置上哈

### ISSUE THREAD

**Issue by Mradxz** [medz/cors#9]
不知道为什么 我设置了 Access-Control-Max-Age
'max-age'            => env('CORS_ACCESS_CONTROL_MAX_AGE', 3600),
但是在返回的包头里 却没有这个值
我用的是 laravel 5.5
浏览器是 360急速版

**Comment by medz** [comment]
好的
我看下


Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2018年10月25日，10:03，Mradxz <notifications@github.com<mailto:notifications@github.com>> 写道：


不知道为什么 我设置了 Access-Control-Max-Age
'max-age' => env('CORS_ACCESS_CONTROL_MAX_AGE', 3600),
但是在返回的包头里 却没有这个值
我用的是 laravel 5.5
浏览器是 360急速版

**Comment by medz** [comment]
![image](https://user-images.githubusercontent.com/5564821/47478645-b03a4600-d85c-11e8-9238-59a83860e3da.png)
@Mradxz sorry, 你提到的问题没有复现～我这里使用 Laravel 框架，然后设置 'max-age' 配置的值，从 headers 里面会返回

**Comment by Mradxz** [comment]
好像是没有正确读取配置文件里的内容
我直接改的 vendor 里的那个配置文件 成功了

**Comment by medz** [comment]
你有执行 vendor：publish 把配置文件发不到  config 文件夹嘛？

Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2018年10月25日，16:05，Mradxz <notifications@github.com<mailto:notifications@github.com>> 写道：


好像是没有正确读取配置文件里的内容
我直接改的 vendor 里的那个配置文件 成功了

**Comment by medz** [comment]
配置文件机制是 laravel 提供的，所以得按照 laravel 的方式把文件发布出去才能覆盖配置的。

Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2018年10月25日，16:05，Mradxz <notifications@github.com<mailto:notifications@github.com>> 写道：


好像是没有正确读取配置文件里的内容
我直接改的 vendor 里的那个配置文件 成功了

**Comment by Mradxz** [comment]
php artisan vendor:publish --provider="Medz\Cors\Laravel\Providers\LaravelServiceProvider" --force
这个我执行了 配置文件也生成了 但是里面的内容没起作用

**Comment by medz** [comment]
你是不是运行了 config:cache 的？我测试了两次，发不到 config/ 目录后修改内容会生效的～

**Comment by Mradxz** [comment]
额 果然是这个原因 不好意思哈
二维码多少 给你发红包

**Comment by medz** [comment]
@Mradxz 哈哈，没事～能解决问题就好～而且你使用这个组件我已经很开心了～谢谢
